/**
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.elastest.epm.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Everything needed for accessing a machine using SSH
 */
@ApiModel(description = "Everything needed for accessing a machine using SSH")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-17T11:20:22.580+01:00")
public class AuthCredentials   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("user")
  private String user = null;

  @SerializedName("passphrase")
  private String passphrase = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("port")
  private Integer port = null;

  public AuthCredentials id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AuthCredentials key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The name of the key saved in EPM, which can be used to execute runtime operations on this VDU.
   * @return key
  **/
  @ApiModelProperty(example = "vdu_1-key", value = "The name of the key saved in EPM, which can be used to execute runtime operations on this VDU.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public AuthCredentials user(String user) {
    this.user = user;
    return this;
  }

   /**
   * This is the user, which the EPM will use when trying to ssh in to the Worker.
   * @return user
  **/
  @ApiModelProperty(example = "ubuntu", required = true, value = "This is the user, which the EPM will use when trying to ssh in to the Worker.")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public AuthCredentials passphrase(String passphrase) {
    this.passphrase = passphrase;
    return this;
  }

   /**
   * This is the Passphrase of the Key provided for connecting to the Worker.
   * @return passphrase
  **/
  @ApiModelProperty(example = "null", value = "This is the Passphrase of the Key provided for connecting to the Worker.")
  public String getPassphrase() {
    return passphrase;
  }

  public void setPassphrase(String passphrase) {
    this.passphrase = passphrase;
  }

  public AuthCredentials password(String password) {
    this.password = password;
    return this;
  }

   /**
   * This is the password of the user, which can be left blank if no password is needed.
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "This is the password of the user, which can be left blank if no password is needed.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public AuthCredentials port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * The ssh port of the worker, where the EPM can reach it.
   * @return port
  **/
  @ApiModelProperty(example = "null", value = "The ssh port of the worker, where the EPM can reach it.")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthCredentials authCredentials = (AuthCredentials) o;
    return Objects.equals(this.id, authCredentials.id) &&
        Objects.equals(this.key, authCredentials.key) &&
        Objects.equals(this.user, authCredentials.user) &&
        Objects.equals(this.passphrase, authCredentials.passphrase) &&
        Objects.equals(this.password, authCredentials.password) &&
        Objects.equals(this.port, authCredentials.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, user, passphrase, password, port);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthCredentials {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    passphrase: ").append(toIndentedString(passphrase)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

