/**
 * EPM REST API REST API description of the ElasTest Platform Manager Module.
 *
 * <p>OpenAPI spec version: 0.1.2
 *
 * <p>NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.elastest.epm.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** ClusterFromResourceGroup */
@javax.annotation.Generated(
  value = "class io.swagger.codegen.languages.JavaClientCodegen",
  date = "2018-12-17T11:20:22.580+01:00"
)
public class ClusterFromResourceGroup {
  @SerializedName("type")
  private List<String> type = new ArrayList<String>();

  @SerializedName("resourceGroupId")
  private String resourceGroupId = null;

  @SerializedName("masterId")
  private String masterId = null;

  public ClusterFromResourceGroup type(List<String> type) {
    this.type = type;
    return this;
  }

  public ClusterFromResourceGroup addTypeItem(String typeItem) {
    this.type.add(typeItem);
    return this;
  }

  /**
   * The types of the worker.
   *
   * @return type
   */
  @ApiModelProperty(example = "null", required = true, value = "The types of the worker.")
  public List<String> getType() {
    return type;
  }

  public void setType(List<String> type) {
    this.type = type;
  }

  public ClusterFromResourceGroup resourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
    return this;
  }

  /**
   * The id of vdu from which to create the worker.
   *
   * @return resourceGroupId
   */
  @ApiModelProperty(
    example = "null",
    required = true,
    value = "The id of vdu from which to create the worker."
  )
  public String getResourceGroupId() {
    return resourceGroupId;
  }

  public void setResourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
  }

  public ClusterFromResourceGroup masterId(String masterId) {
    this.masterId = masterId;
    return this;
  }

  /**
   * The ID of the VDU which will serve as the master node. This should be an ID of a VDU which
   * belongs to the specified Ressource Group.
   *
   * @return masterId
   */
  @ApiModelProperty(
    example = "null",
    required = true,
    value =
        "The ID of the VDU which will serve as the master node. This should be an ID of a VDU which belongs to the specified Ressource Group."
  )
  public String getMasterId() {
    return masterId;
  }

  public void setMasterId(String masterId) {
    this.masterId = masterId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterFromResourceGroup clusterFromResourceGroup = (ClusterFromResourceGroup) o;
    return Objects.equals(this.type, clusterFromResourceGroup.type)
        && Objects.equals(this.resourceGroupId, clusterFromResourceGroup.resourceGroupId)
        && Objects.equals(this.masterId, clusterFromResourceGroup.masterId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, resourceGroupId, masterId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterFromResourceGroup {\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    resourceGroupId: ").append(toIndentedString(resourceGroupId)).append("\n");
    sb.append("    masterId: ").append(toIndentedString(masterId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
