/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.elastest.epm.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.elastest.epm.client.model.Worker;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Cluster
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-09T15:22:36.559+02:00")
public class Cluster {
  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("master")
  private Worker master = null;

  @SerializedName("nodes")
  private List<Worker> nodes = null;

  @SerializedName("resourceGroupId")
  private String resourceGroupId = null;

  public Cluster id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Cluster type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the Cluster.
   * @return type
  **/
  @ApiModelProperty(example = "kubernetes", required = true, value = "Type of the Cluster.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Cluster key(String key) {
    this.key = key;
    return this;
  }

   /**
   * This is the key itself as String.
   * @return key
  **/
  @ApiModelProperty(value = "This is the key itself as String.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Cluster master(Worker master) {
    this.master = master;
    return this;
  }

   /**
   * Get master
   * @return master
  **/
  @ApiModelProperty(value = "")
  public Worker getMaster() {
    return master;
  }

  public void setMaster(Worker master) {
    this.master = master;
  }

  public Cluster nodes(List<Worker> nodes) {
    this.nodes = nodes;
    return this;
  }

  public Cluster addNodesItem(Worker nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<Worker>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @ApiModelProperty(value = "")
  public List<Worker> getNodes() {
    return nodes;
  }

  public void setNodes(List<Worker> nodes) {
    this.nodes = nodes;
  }

  public Cluster resourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
    return this;
  }

   /**
   * Get resourceGroupId
   * @return resourceGroupId
  **/
  @ApiModelProperty(value = "")
  public String getResourceGroupId() {
    return resourceGroupId;
  }

  public void setResourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cluster cluster = (Cluster) o;
    return Objects.equals(this.id, cluster.id) &&
        Objects.equals(this.type, cluster.type) &&
        Objects.equals(this.key, cluster.key) &&
        Objects.equals(this.master, cluster.master) &&
        Objects.equals(this.nodes, cluster.nodes) &&
        Objects.equals(this.resourceGroupId, cluster.resourceGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, key, master, nodes, resourceGroupId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cluster {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    resourceGroupId: ").append(toIndentedString(resourceGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

