/**
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.elastest.epm.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Cluster
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-17T11:20:22.580+01:00")
public class Cluster   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("master")
  private Worker master = null;

  @SerializedName("nodes")
  private List<Worker> nodes = new ArrayList<Worker>();

  @SerializedName("resourceGroupId")
  private String resourceGroupId = null;

  public Cluster id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Cluster type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the Cluster.
   * @return type
  **/
  @ApiModelProperty(example = "kubernetes", required = true, value = "Type of the Cluster.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Cluster master(Worker master) {
    this.master = master;
    return this;
  }

   /**
   * Get master
   * @return master
  **/
  @ApiModelProperty(example = "null", value = "")
  public Worker getMaster() {
    return master;
  }

  public void setMaster(Worker master) {
    this.master = master;
  }

  public Cluster nodes(List<Worker> nodes) {
    this.nodes = nodes;
    return this;
  }

  public Cluster addNodesItem(Worker nodesItem) {
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Worker> getNodes() {
    return nodes;
  }

  public void setNodes(List<Worker> nodes) {
    this.nodes = nodes;
  }

  public Cluster resourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
    return this;
  }

   /**
   * Get resourceGroupId
   * @return resourceGroupId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceGroupId() {
    return resourceGroupId;
  }

  public void setResourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cluster cluster = (Cluster) o;
    return Objects.equals(this.id, cluster.id) &&
        Objects.equals(this.type, cluster.type) &&
        Objects.equals(this.master, cluster.master) &&
        Objects.equals(this.nodes, cluster.nodes) &&
        Objects.equals(this.resourceGroupId, cluster.resourceGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, master, nodes, resourceGroupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cluster {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    resourceGroupId: ").append(toIndentedString(resourceGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

