/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.elastest.epm.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CommandExecutionBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T16:53:27.371+02:00")
public class CommandExecutionBody {
  @SerializedName("command")
  private String command = null;

  @SerializedName("awaitCompletion")
  private Boolean awaitCompletion = null;

  public CommandExecutionBody command(String command) {
    this.command = command;
    return this;
  }

   /**
   * Get command
   * @return command
  **/
  @ApiModelProperty(example = "ls /", required = true, value = "")
  public String getCommand() {
    return command;
  }

  public void setCommand(String command) {
    this.command = command;
  }

  public CommandExecutionBody awaitCompletion(Boolean awaitCompletion) {
    this.awaitCompletion = awaitCompletion;
    return this;
  }

   /**
   * Get awaitCompletion
   * @return awaitCompletion
  **/
  @ApiModelProperty(example = "true", required = true, value = "")
  public Boolean getAwaitCompletion() {
    return awaitCompletion;
  }

  public void setAwaitCompletion(Boolean awaitCompletion) {
    this.awaitCompletion = awaitCompletion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandExecutionBody commandExecutionBody = (CommandExecutionBody) o;
    return Objects.equals(this.command, commandExecutionBody.command) &&
        Objects.equals(this.awaitCompletion, commandExecutionBody.awaitCompletion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(command, awaitCompletion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandExecutionBody {\n");

    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    awaitCompletion: ").append(toIndentedString(awaitCompletion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

