/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.elastest.epm.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * A Resource Group defines a bundle of VDUs and virtual networks which belongs together. It includes also the Point-of-Presences where the virtual resources have to be allocated.
 */
@ApiModel(description = "A Resource Group defines a bundle of VDUs and virtual networks which belongs together. It includes also the Point-of-Presences where the virtual resources have to be allocated.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-21T16:11:00.478+02:00")
public class ResourceGroup {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("vdus")
  private List<VDU> vdus = new ArrayList<VDU>();

  @SerializedName("networks")
  private List<Network> networks = new ArrayList<Network>();

  @SerializedName("pops")
  private List<PoP> pops = new ArrayList<PoP>();

  public ResourceGroup id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1234-abcd", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResourceGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "testResourceGroupName1", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceGroup vdus(List<VDU> vdus) {
    this.vdus = vdus;
    return this;
  }

  public ResourceGroup addVdusItem(VDU vdusItem) {
    this.vdus.add(vdusItem);
    return this;
  }

   /**
   * Get vdus
   * @return vdus
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<VDU> getVdus() {
    return vdus;
  }

  public void setVdus(List<VDU> vdus) {
    this.vdus = vdus;
  }

  public ResourceGroup networks(List<Network> networks) {
    this.networks = networks;
    return this;
  }

  public ResourceGroup addNetworksItem(Network networksItem) {
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Get networks
   * @return networks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Network> getNetworks() {
    return networks;
  }

  public void setNetworks(List<Network> networks) {
    this.networks = networks;
  }

  public ResourceGroup pops(List<PoP> pops) {
    this.pops = pops;
    return this;
  }

  public ResourceGroup addPopsItem(PoP popsItem) {
    this.pops.add(popsItem);
    return this;
  }

   /**
   * Get pops
   * @return pops
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PoP> getPops() {
    return pops;
  }

  public void setPops(List<PoP> pops) {
    this.pops = pops;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceGroup resourceGroup = (ResourceGroup) o;
    return Objects.equals(this.id, resourceGroup.id) &&
        Objects.equals(this.name, resourceGroup.name) &&
        Objects.equals(this.vdus, resourceGroup.vdus) &&
        Objects.equals(this.networks, resourceGroup.networks) &&
        Objects.equals(this.pops, resourceGroup.pops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, vdus, networks, pops);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vdus: ").append(toIndentedString(vdus)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    pops: ").append(toIndentedString(pops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

