/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.elastest.epm.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.elastest.epm.client.model.Event;
import io.elastest.epm.client.model.KeyValuePair;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A Virtual Deployment Unit (VDU) describes the capabilities of virtualized computing (Containers, VMs) and networking resources.
 */
@ApiModel(description = "A Virtual Deployment Unit (VDU) describes the capabilities of virtualized computing (Containers, VMs) and networking resources.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-09T12:26:11.755+02:00")
public class VDU {
  @SerializedName("computeId")
  private String computeId = null;

  @SerializedName("events")
  private List<Event> events = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("imageName")
  private String imageName = null;

  @SerializedName("ip")
  private String ip = null;

  @SerializedName("metadata")
  private List<KeyValuePair> metadata = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("netName")
  private String netName = null;

  @SerializedName("poPName")
  private String poPName = null;

  /**
   * The status of the virtualized compute resource.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    INITIALIZING("initializing"),
    
    INITIALIZED("initialized"),
    
    DEPLOYING("deploying"),
    
    DEPLOYED("deployed"),
    
    RUNNING("running"),
    
    UNDEPLOYING("undeploying"),
    
    UNDEPLOYED("undeployed"),
    
    ERROR("error");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("key")
  private String key = null;

  public VDU computeId(String computeId) {
    this.computeId = computeId;
    return this;
  }

   /**
   * The identifier of the deployed VDU in the virtualization technology.
   * @return computeId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the deployed VDU in the virtualization technology.")
  public String getComputeId() {
    return computeId;
  }

  public void setComputeId(String computeId) {
    this.computeId = computeId;
  }

  public VDU events(List<Event> events) {
    this.events = events;
    return this;
  }

  public VDU addEventsItem(Event eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<Event>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * A list of events recorded for this VDU.
   * @return events
  **/
  @ApiModelProperty(value = "A list of events recorded for this VDU.")
  public List<Event> getEvents() {
    return events;
  }

  public void setEvents(List<Event> events) {
    this.events = events;
  }

  public VDU id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of the VDU in the EPM.
   * @return id
  **/
  @ApiModelProperty(value = "The identifier of the VDU in the EPM.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VDU imageName(String imageName) {
    this.imageName = imageName;
    return this;
  }

   /**
   * The name of the image used for the VDU.
   * @return imageName
  **/
  @ApiModelProperty(example = "testImage1", required = true, value = "The name of the image used for the VDU.")
  public String getImageName() {
    return imageName;
  }

  public void setImageName(String imageName) {
    this.imageName = imageName;
  }

  public VDU ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * The IP assigned to the VDU.
   * @return ip
  **/
  @ApiModelProperty(example = "172.0.0.1", required = true, value = "The IP assigned to the VDU.")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public VDU metadata(List<KeyValuePair> metadata) {
    this.metadata = metadata;
    return this;
  }

  public VDU addMetadataItem(KeyValuePair metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<KeyValuePair>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

   /**
   * More detailed information about the VDU in a Key-Value pair format.
   * @return metadata
  **/
  @ApiModelProperty(value = "More detailed information about the VDU in a Key-Value pair format.")
  public List<KeyValuePair> getMetadata() {
    return metadata;
  }

  public void setMetadata(List<KeyValuePair> metadata) {
    this.metadata = metadata;
  }

  public VDU name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the VDU.
   * @return name
  **/
  @ApiModelProperty(example = "testVdu1", required = true, value = "The name of the VDU.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VDU netName(String netName) {
    this.netName = netName;
    return this;
  }

   /**
   * The name of the network to which the VDU is associated with.
   * @return netName
  **/
  @ApiModelProperty(example = "testNetworkName", required = true, value = "The name of the network to which the VDU is associated with.")
  public String getNetName() {
    return netName;
  }

  public void setNetName(String netName) {
    this.netName = netName;
  }

  public VDU poPName(String poPName) {
    this.poPName = poPName;
    return this;
  }

   /**
   * The name of the PoP where the VDU is deployed.
   * @return poPName
  **/
  @ApiModelProperty(required = true, value = "The name of the PoP where the VDU is deployed.")
  public String getPoPName() {
    return poPName;
  }

  public void setPoPName(String poPName) {
    this.poPName = poPName;
  }

  public VDU status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the virtualized compute resource.
   * @return status
  **/
  @ApiModelProperty(value = "The status of the virtualized compute resource.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public VDU key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The name of the key saved in EPM, which can be used to execute runtime operations on this VDU.
   * @return key
  **/
  @ApiModelProperty(example = "vdu_1-key", value = "The name of the key saved in EPM, which can be used to execute runtime operations on this VDU.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VDU VDU = (VDU) o;
    return Objects.equals(this.computeId, VDU.computeId) &&
        Objects.equals(this.events, VDU.events) &&
        Objects.equals(this.id, VDU.id) &&
        Objects.equals(this.imageName, VDU.imageName) &&
        Objects.equals(this.ip, VDU.ip) &&
        Objects.equals(this.metadata, VDU.metadata) &&
        Objects.equals(this.name, VDU.name) &&
        Objects.equals(this.netName, VDU.netName) &&
        Objects.equals(this.poPName, VDU.poPName) &&
        Objects.equals(this.status, VDU.status) &&
        Objects.equals(this.key, VDU.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(computeId, events, id, imageName, ip, metadata, name, netName, poPName, status, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VDU {\n");
    
    sb.append("    computeId: ").append(toIndentedString(computeId)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    netName: ").append(toIndentedString(netName)).append("\n");
    sb.append("    poPName: ").append(toIndentedString(poPName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

