/**
 * EPM REST API REST API description of the ElasTest Platform Manager Module.
 *
 * <p>OpenAPI spec version: 0.1.2
 *
 * <p>NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.elastest.epm.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Worker */
@javax.annotation.Generated(
  value = "class io.swagger.codegen.languages.JavaClientCodegen",
  date = "2018-12-17T11:20:22.580+01:00"
)
public class Worker {
  @SerializedName("id")
  private String id = null;

  @SerializedName("ip")
  private String ip = null;

  @SerializedName("vduId")
  private String vduId = null;

  @SerializedName("epmIp")
  private String epmIp = null;

  @SerializedName("type")
  private List<String> type = new ArrayList<String>();

  @SerializedName("authCredentials")
  private AuthCredentials authCredentials = null;

  public Worker id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Worker ip(String ip) {
    this.ip = ip;
    return this;
  }

  /**
   * Get ip
   *
   * @return ip
   */
  @ApiModelProperty(example = "null", value = "")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public Worker vduId(String vduId) {
    this.vduId = vduId;
    return this;
  }

  /**
   * The vduId if the worker was created from a vdu.
   *
   * @return vduId
   */
  @ApiModelProperty(example = "null", value = "The vduId if the worker was created from a vdu.")
  public String getVduId() {
    return vduId;
  }

  public void setVduId(String vduId) {
    this.vduId = vduId;
  }

  public Worker epmIp(String epmIp) {
    this.epmIp = epmIp;
    return this;
  }

  /**
   * This is the IP where the EPM is reachable for the Worker. This is needed because the Worker has
   * to be able to reach the EPM for registering adapters.
   *
   * @return epmIp
   */
  @ApiModelProperty(
    example = "null",
    value =
        "This is the IP where the EPM is reachable for the Worker. This is needed because the Worker has to be able to reach the EPM for registering adapters."
  )
  public String getEpmIp() {
    return epmIp;
  }

  public void setEpmIp(String epmIp) {
    this.epmIp = epmIp;
  }

  public Worker type(List<String> type) {
    this.type = type;
    return this;
  }

  public Worker addTypeItem(String typeItem) {
    this.type.add(typeItem);
    return this;
  }

  /**
   * The types which this worker supports at the moment when this information is requested.
   *
   * @return type
   */
  @ApiModelProperty(
    example = "null",
    value = "The types which this worker supports at the moment when this information is requested."
  )
  public List<String> getType() {
    return type;
  }

  public void setType(List<String> type) {
    this.type = type;
  }

  public Worker authCredentials(AuthCredentials authCredentials) {
    this.authCredentials = authCredentials;
    return this;
  }

  /**
   * Get authCredentials
   *
   * @return authCredentials
   */
  @ApiModelProperty(example = "null", value = "")
  public AuthCredentials getAuthCredentials() {
    return authCredentials;
  }

  public void setAuthCredentials(AuthCredentials authCredentials) {
    this.authCredentials = authCredentials;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Worker worker = (Worker) o;
    return Objects.equals(this.id, worker.id)
        && Objects.equals(this.ip, worker.ip)
        && Objects.equals(this.vduId, worker.vduId)
        && Objects.equals(this.epmIp, worker.epmIp)
        && Objects.equals(this.type, worker.type)
        && Objects.equals(this.authCredentials, worker.authCredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ip, vduId, epmIp, type, authCredentials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Worker {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    vduId: ").append(toIndentedString(vduId)).append("\n");
    sb.append("    epmIp: ").append(toIndentedString(epmIp)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    authCredentials: ").append(toIndentedString(authCredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
