/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.elastest.epm.client.api;

import io.elastest.epm.client.ApiException;
import io.elastest.epm.client.model.Key;
import java.util.List;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for KeyApi */
@Ignore
public class KeyApiTest {

  private final KeyApi api = new KeyApi();

  /**
   * Uploads a key to the EPM.
   *
   * <p>This uploads a key to the EPM, so it can be later used when registering workers.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void addKeyTest() throws ApiException {
    Key body = null;
    Key response = api.addKey(body);

    // TODO: test validations
  }

  /**
   * Deletes a Key.
   *
   * <p>Deletes the Key that matches with a given ID.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void deleteKeyTest() throws ApiException {
    String id = null;
    String response = api.deleteKey(id);

    // TODO: test validations
  }

  /**
   * Returns all available Keys
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getAllKeysTest() throws ApiException {
    List<Key> response = api.getAllKeys();
    System.out.print(response);
  }
}
