/*
 * EPM REST API
 * REST API description of the ElasTest Platform Manager Module.
 *
 * OpenAPI spec version: 0.1.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.elastest.epm.client.api;

import io.elastest.epm.client.ApiClient;
import io.elastest.epm.client.ApiException;
import io.elastest.epm.client.model.ResourceGroup;
import java.io.File;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.LoggerFactory;

/** API tests for PackageApi */
@Ignore
public class PackageApiTest {

  private final PackageApi api = new PackageApi();
  private org.slf4j.Logger log = LoggerFactory.getLogger(this.getClass());

  @Before
  public void init() {
    ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:8180/v1");
    api.setApiClient(apiClient);
  }

  /**
   * Deletes a package.
   *
   * <p>Deletes the package that matches with a given ID.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void deletePackageTest() throws ApiException {
    String id = null;
    api.deletePackage(id);

    // TODO: test validations
  }

  /**
   * Receives a package.
   *
   * <p>Receives a package so that it can be forwarded to the correct environment.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  @Ignore
  public void receivePackageTest() throws ApiException {
    File testPackage =
        new File(getClass().getClassLoader().getResource("compose-package.tar").getPath());
    ResourceGroup resourceGroup = api.receivePackage(testPackage);
    log.info(String.valueOf(resourceGroup));
  }
}
